# model_evaluation

### Why
- Minimizing false positives --> Precision
- Minimizing false negatives --> Recall
- Both Precision and Recall --> F1 score
- ----------------------------------------

- **accuracy**: (TP + TN) / (TP + TN + FP + FN)
- **precision**: TP / (TP + FP)  
- **recall**: TP / (TP + FN)

## Given the following confusion matrix, evaluate (by hand) the model's performance.


- |               | pred dog   | pred cat   |
- |:------------  |-----------:|-----------:|
- | actual dog    |         46 |         7  |
- | actual cat    |         13 |         34 |
- In the context of this problem, what is a false positive?
- In the context of this problem, what is a false negative?
- How would you describe this model?


##### 
- FP = 13
- FN = 7
- This model is a cat dog predictor

## You are working as a datascientist working for Codeup Cody Creator (C3 for short), a rubber-duck manufacturing plant.

- Unfortunately, some of the rubber ducks that are produced will have defects. Your team has built several models that try to predict those defects, and the data from their predictions can be found here.

- Use the predictions dataset and pandas to help answer the following questions:

- An internal team wants to investigate the cause of the manufacturing defects. They tell you that they want to identify as many of the ducks that have a defect as possible. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?
- **We want to minimize false positives so we want to emphasize precition** 
- Recently several stories in the local news have come out highlighting customers who received a rubber duck with a defect, and portraying C3 in a bad light. The PR team has decided to launch a program that gives customers with a defective duck a vacation to Hawaii. They need you to predict which ducks will have defects, but tell you the really don't want to accidentally give out a vacation package when the duck really doesn't have a defect. Which evaluation metric would be appropriate here? Which model would be the best fit for this use case?
- **Model 1 produces the best results in acuracy and precision**

In [8]:
import pandas as pd
import numpy as np
import sklearn.metrics as sk

In [2]:
c_df = pd.read_csv('c3.csv')
c_df.head()

actual     model1  model2     model3
0  No Defect  No Defect  Defect  No Defect
1  No Defect  No Defect  Defect     Defect
2  No Defect  No Defect  Defect  No Defect
3  No Defect     Defect  Defect     Defect
4  No Defect  No Defect  Defect  No Defect

In [3]:
c_df.shape

(200, 4)

### Model compare

#### Model 1

In [5]:
# Model 1 vs Actual
pd.crosstab(c_df.actual, c_df.model1)

model1     Defect  No Defect
actual                      
Defect          8          8
No Defect       2        182

In [19]:
# Accuracy
sk.accuracy_score(c_df.actual, c_df.model1)

0.95

In [12]:
# precision: TP / (TP + FP)
8 / (8 + 2)

0.8

In [11]:
# Precision
sk.precision_score(c_df.actual, c_df.model1, average=None)

array([0.8       , 0.95789474])

#### Model 2

In [6]:
# Model 2 vs Actual
pd.crosstab(c_df.actual, c_df.model2)

model2     Defect  No Defect
actual                      
Defect          9          7
No Defect      81        103

In [20]:
# Accuracy
sk.accuracy_score(c_df.actual, c_df.model2)

0.56

In [14]:
# precision: TP / (TP + FP)
9 / (9 + 81)

0.1

In [13]:
# Precision
sk.precision_score(c_df.actual, c_df.model2, average=None)

array([0.1       , 0.93636364])

#### Model 3

In [7]:
# Model 3 vs Actual
pd.crosstab(c_df.actual, c_df.model3)

model3     Defect  No Defect
actual                      
Defect         13          3
No Defect      86         98

In [21]:
# Accuracy
sk.accuracy_score(c_df.actual, c_df.model3)

0.555

In [18]:
# precision: TP / (TP + FP)
13 / (13 + 86)

0.13131313131313133

In [17]:
# Precision
sk.precision_score(c_df.actual, c_df.model3, average=None)

array([0.13131313, 0.97029703])

## You are working as a data scientist for Gives You Paws ™, a subscription based service that shows you cute pictures of dogs or cats (or both for an additional fee).

- At Gives You Paws, anyone can upload pictures of their cats or dogs. The photos are then put through a two step process. First an automated algorithm tags pictures as either a cat or a dog (Phase I). Next, the photos that have been initially identified are put through another round of review, possibly with some human oversight, before being presented to the users (Phase II).

- Several models have already been developed with the data, and you can find their results here.

- Given this dataset, use pandas to create a baseline model (i.e. a model that just predicts the most common class) and answer the following questions:

- In terms of accuracy, how do the various models compare to the baseline model? Are any of the models better than the baseline?
- Suppose you are working on a team that solely deals with dog pictures. Which of these models would you recomend for Phase I? For Phase II?
- Suppose you are working on a team that solely deals with cat pictures. Which of these models would you recomend for Phase I? For Phase II?


In [22]:
paws_df = pd.read_csv('gives_you_paws.csv')
paws_df.head()

actual model1 model2 model3 model4
0    cat    cat    dog    cat    dog
1    dog    dog    cat    cat    dog
2    dog    cat    cat    cat    dog
3    dog    dog    dog    cat    dog
4    cat    cat    cat    dog    dog

In [24]:
paws_df.shape

(5000, 5)

In [25]:
paws_df.actual.value_counts()

dog    3254
cat    1746
Name: actual, dtype: int64

In [26]:
paws_df['baseline_prediction'] = 'dog'
paws_df.head()

actual model1 model2 model3 model4 baseline_prediction
0    cat    cat    dog    cat    dog                 dog
1    dog    dog    cat    cat    dog                 dog
2    dog    cat    cat    cat    dog                 dog
3    dog    dog    dog    cat    dog                 dog
4    cat    cat    cat    dog    dog                 dog

In [27]:
(paws_df.actual == paws_df.baseline_prediction).mean()

0.6508

### Model Compare

#### Model 1

In [28]:
sk.accuracy_score(paws_df.actual, paws_df.model1)

0.8074

#### Model 2

#### Model 3

#### Model 4

## Follow the links below to read the documentation about each function, then apply those functions to the data from the previous problem.

- sklearn.metrics.accuracy_score
- sklearn.metrics.precision_score
- sklearn.metrics.recall_score
- sklearn.metrics.classification_report